apiVersion: extensions/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: oms-deployment
spec:
  selector:
    matchLabels:
      app: oms
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: oms
    spec:
      containers:
      - name: oms
        image: dcap/minnietwitter:latest
        ports:
        - containerPort: 32557 # kernelserverport
        - containerPort: 32555 # rmiport
        command: ["/root/dcap/start-oms.sh"]
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: oms-rmi-svc
spec:
  type: NodePort
  ports:
  - port: 32555
    targetPort: 32555
    nodePort: 32555
    protocol: TCP
  selector:
    app: oms
---
apiVersion: v1
kind: Service
metadata:
  name: oms-svc
spec:
  type: NodePort
  ports:
  - port: 32557
    targetPort: 32557
    nodePort: 32557
    protocol: TCP
  selector:
    app: oms

